# Generated by Django 5.2.1 on 2025-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelovehiculo',
            name='es_premium',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
