# Generated by Django 5.2.1 on 2025-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_historialestadoalquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
