# Generated by Django 5.2.1 on 2025-06-07 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_provincia_departamento_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='alquiler.departamento'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='alquiler.localidad'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='alquiler.provincia'),
        ),
    ]
