# Generated by Django 5.2.1 on 2025-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_alter_sucursal_departamento_alter_sucursal_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
    ]
