"""
Django settings for alquiler_vehiculos project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""



from pathlib import Path

from apps import alquiler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import sys
import os
sys.path.append(os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=-o_6$4w17q^r9@svh&-j7132aj3%%g*icj-91p%0tyrbmf4@)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

    'django_filters',

    'apps.alquiler',
    'apps.usuario',

    'drf_spectacular',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alquiler_vehiculos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'apps/alquiler/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alquiler_vehiculos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'apps/alquiler/static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'usuario.Usuario'



REST_FRAMEWORK = {

#-------------------------VERSIONADO-------------------------------------#
#                                                                        #
#------------------------------------------------------------------------#
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',

#-------------------------FILTROS Y ORDEN--------------------------------#
#                                                                        #
#------------------------------------------------------------------------#

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],


#-------------------------CANTIDAD DE PAGINAS----------------------------#
#cantidad de paginas por vista                                           #
#------------------------------------------------------------------------#

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, #cantidad que se va a mostrar por pagina


#---------------------------------------RENDERIZADO-------------------------------#
# DEFAULT_RENDERER_CLASSES se configura el conjunto predeterminado de             #
# renderizadores (es decir, el formato de la respuesta que se envía al cliente).  #
#---------------------------------------------------------------------------------#

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer'
    ],


#-----------------------------AUTENTICACION------------------------------#
#                                     JWT                                #
#------------------------------------------------------------------------#

     'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework_simplejwt.authentication.JWTAuthentication',
     ),

#-----------------------------AUTORIZACION-------------------------------#
#                                                                        #
#------------------------------------------------------------------------#
    #'DEFAULT_PERMISSION_CLASSES': [
    #  'rest_framework.permissions.DjangoModelPermissions',
    #  ],


      'DEFAULT_PERMISSION_CLASSES': [
           'alquiler_vehiculos.permissions.StrictModelPermissions',
      ],

#-----------------------------DOCUMENTACION-------------------------------#
#                                                                        #
#------------------------------------------------------------------------#
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',


} #termina rest framework

from datetime import timedelta


SIMPLE_JWT = {
    'SIGNING_KEY': SECRET_KEY, # Presente por defecto en settings
    'ALGORITHM': 'HS256', # Algoritmo de firma
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=45),  # tiempo del token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


#para mostrar los menajes de error en español
LANGUAGE_CODE = 'es'

USE_I18N = True
